name: CI/CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  CleanWorkdir:
    runs-on: self-hosted
    steps: 
      - name: clean
        run: rm -rf ./*
 
  Codestyle:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
 
      - name: Install dependencies
        run: pip3 install flake8
 
      - name: CodeStyle
        run: python3 -m flake8 ./ --ignore=F401,E402
 
 
  Tests:
  
    runs-on: self-hosted
    needs: Codestyle
    steps:
      - uses: actions/checkout@v2
 
      - name: Tests
        run: |
          pip3 install -e '.[test]'
          python3 -m coverage run -m pytest
          python3 -m coverage html -d coverage_html
 
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: coverage_html
          retention-days: 1
 
  DockerHub:
    needs: Tests
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker
        run: |
          docker build -t edan9902/app .
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push edan9902/app
 
  Deployment:
    needs: DockerHub
    runs-on: self-hosted
    steps:
      - name: run latest version
        run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker rm -f current_version
          docker run -d --name current_version edan9902/app:latest
 
